### ISSUE TITLE
Racism and the "load_boston" dataset

### ISSUE THREAD

**Issue by koaning** [BCG-Gamma/facet#202]
I just read the announcement of this project [here](https://www.bcg.com/press/12january2021-facet-open-source-library-for-human-explainable-artificial-intelligence). This quote can be found; 

> BCG GAMMA FACET Helps Human Operators Understand Advanced Machine Learning Models So They Can Make Better and More Ethical Decisions

When I go to this repo (which isn't linked in the blog post by the way) I find a demo that is using the `load_boston` dataset to explain how to use the tool. It seems to focus on the `LSTAT` attribute of this dataset while it fails to acknowledge a bigger issue related to ethics, namely the `B` attribute. According to the [docs](https://scikit-learn.org/stable/datasets/toy_dataset.html#boston-dataset) it refers to: 

>B 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town

Given that this tool is marketed with themes of ethics and understanding, and that it is backed by an international consultancy company, this is really not cool. This tool is marketed to help people make more ethical decisions. So why does the guide present a model that uses skin color to determine house prices without mentioning it? For a guide that could be seen as an authoritative source on how to handle "ethical decisions" this is really dubious. 

Note that this [dataset is up for removal from scikit-learn](https://github.com/scikit-learn/scikit-learn/issues/16155) because of [this controversy](https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8) and it's also something that's been pointed out at many conferences. [Here](https://www.youtube.com/watch?v=Z8MEFI7ZJlA&t=211s&ab_channel=PyData) is one talk from me if you're interested. 

Please replace the guide with an example that is more fitting or at the very least acknowledges the issues with the variable.

**Comment by j-ittner** [comment]
Hi @koaning , thank you for pointing out the issues around the “B” attribute and for highlighting that the dataset is up for removal on scikit-learn. We have discussed this in the team and will take immediate steps to remove the dataset and update the guide. Thanks!

**Comment by koaning** [comment]
One final comment I might add, how effective can we judge a tool to help at the "Understand Advanced Machine Learning Models So They Can Make Better and More Ethical Decisions"-task if this didn't get spotted? 

I'm mentioning this, explicitly, because the BCG brand is attached. One can expect this tool to be used by a lot of clients and a lot of harm can be done with the wrong attitude. It'd be a shame if people consider a python library as a checkbox so that they no longer need to think about their data.
