### ISSUE TITLE
Run times are huge 

### ISSUE THREAD

**Issue by ghost** [BCG-Gamma/facet#215]
**Describe the bug**
I am using a dataset with 130 columns and the 1000 rows. The below steps keeps on running for more than an hour with no results produced 

I also tried with just 20 columns and 500 rows. the behavior is the same. 
 
step 1 :
``` python
from facet.inspection import LearnerInspector
inspector = LearnerInspector()
inspector.fit(crossfit=ranker.best_model_crossfit_)
```

step2: 
``` python
boot_crossfit = LearnerCrossfit(
    pipeline=ranker.best_model_,
    cv=bscv,
    n_jobs=-3,
    verbose=True,
).fit(sample=df_sample)
```

**Desktop (please complete the following information):**
 - OS: [MacOS]

**Comment by j-ittner** [comment]
Hi!

Happy to help - which of the steps is taking long?
Could you please also share the CV strategy you used for the crossfit in step 1 - how many CV splits does it contain?

Thanks!

**Comment by ghost** [comment]
Hi, 

I am using the same specs as given in the sample code. I have just changed the diabetes data to my data. The only difference is that mine is a classification model hence I have changed classes to "classifier"

**Comment by j-ittner** [comment]
Hmm … let's dig a bit deeper. Is it step 1 or step 2 that keeps running?

- could you please share the complete code, even if based on copy/paste from the sample code?
- can you please try creating the LearnerInspector using `LearnerInspector(n_jobs=-3, verbose=2)` then re-running step 1?

Thanks!

**Comment by ghost** [comment]
# standard imports
import pandas as pd
from sklearn.model_selection import RepeatedKFold

# some helpful imports from sklearndf
from sklearndf.pipeline import RegressorPipelineDF
from sklearndf.regression import RandomForestRegressorDF

from sklearndf.pipeline import ClassifierPipelineDF
from sklearndf.classification import RandomForestClassifierDF

# relevant FACET imports
from facet.data import Sample
from facet.selection import LearnerRanker, LearnerGrid


# load the diabetes dataset
df = pd.read_csv('df.csv')
df = df.drop(columns=['Unnamed: 0'])

TARGET='modelling_tag'
df_pos = df[df[TARGET] == 1]
print(f"Info : Length of Positive samples : {len(df_pos)}")

df_neg = df[df[TARGET] == 0]
print(f"Info : Length of Positive samples : {len(df_pos)}")

df_pos = df_pos.sample(n=500, random_state=1)
print(f"Info : Length of Positive samples : {len(df_pos)}")

df_neg = df_neg.sample(n=len(df_pos), random_state=1)
print(f"Info : Length of Negative samples : {len(df_neg)}")

df = df_pos.append(df_neg, ignore_index=True)

# create FACET sample object
df_sample = Sample(observations=df, target_name="modelling_tag")

# create a (trivial) pipeline for a random forest regressor
rnd_forest_reg = ClassifierPipelineDF(
    classifier=RandomForestClassifierDF(random_state=42)
)



# define grid of models which are "competing" against each other
rnd_forest_grid = [
    LearnerGrid(
        pipeline=rnd_forest_reg,
        learner_parameters={
            "min_samples_leaf": [8, 11, 15]
        }
    ),
]

# create repeated k-fold CV iterator
rkf_cv = RepeatedKFold(n_splits=5, n_repeats=10, random_state=42)

# rank your candidate models by performance (default is mean CV score - 2*SD)
ranker = LearnerRanker(
    grids=rnd_forest_grid, cv=rkf_cv, n_jobs=-3
).fit(sample=df_sample)

# get summary report
ranker.summary_report()


# fit the model inspector
from facet.inspection import LearnerInspector
inspector = LearnerInspector()
inspector.fit(crossfit=ranker.best_model_crossfit_)


# visualise synergy as a matrix
from pytools.viz.matrix import MatrixDrawer
synergy_matrix = inspector.feature_synergy_matrix()
MatrixDrawer(style="matplot%").draw(synergy_matrix, title="Synergy Matrix")


# visualise redundancy as a matrix
redundancy_matrix = inspector.feature_redundancy_matrix()
MatrixDrawer(style="matplot%").draw(redundancy_matrix, title="Redundancy Matrix")


# visualise redundancy using a dendrogram
from pytools.viz.dendrogram import DendrogramDrawer
redundancy = inspector.feature_redundancy_linkage()
DendrogramDrawer().draw(data=redundancy, title="Redundancy Dendrogram")

# FACET imports
from facet.validation import BootstrapCV
from facet.crossfit import LearnerCrossfit
from facet.simulation import UnivariateUpliftSimulator
from facet.simulation.partition import ContinuousRangePartitioner
from facet.simulation.viz import SimulationDrawer

# create bootstrap CV iterator
bscv = BootstrapCV(n_splits=1000, random_state=42)

# create a bootstrap CV crossfit for simulation using best model
boot_crossfit = LearnerCrossfit(
    pipeline=ranker.best_model_,
    cv=bscv,
    n_jobs=-3,
    verbose=True,
).fit(sample=df_sample)

SIM_FEAT = "coupons_ichiba"
simulator = UnivariateUpliftSimulator(crossfit=boot_crossfit, n_jobs=-3)

# split the simulation range into equal sized partitions
partitioner = ContinuousRangePartitioner()

# run the simulation
simulation = simulator.simulate_feature(feature_name=SIM_FEAT, partitioner=partitioner)

# visualise results
SimulationDrawer().draw(data=simulation, title=SIM_FEAT)

**Comment by ghost** [comment]
I ran with suggested specifications for step 1  it is still running for a longer period of time. In my opinion for a dataset with 20 variables and 1000 observations (earlier I took 130 variables but now reduced to 20 only) it should not take more than a few seconds. 

Also while running simulator I am getting the below error 
TypeError: arg crossfit must fit a pipeline of type RegressorPipelineDF.
This might be due to the fact that I have used a ClassifierPipelineDF. is the simulator only for regression ?

**Comment by j-ittner** [comment]
uplift simulations require a regression model (see [here](https://bcg-gamma.github.io/facet/apidoc/facet/simulation/facet.simulation.UnivariateUpliftSimulator.html))
for classification, use a [`UnivariateProbabilitySimulator`](https://bcg-gamma.github.io/facet/apidoc/facet/simulation/facet.simulation.UnivariateProbabilitySimulator.html)

**Comment by j-ittner** [comment]
Re step 1 taking long, could you please create a learner inspector using the parameters above (`n_jobs=-3, verbose=2`) and share the log messages?

**Comment by ghost** [comment]
Hi, 

Thanks a lot for your help. It works fine with LearnerInspector(n_jobs=-3, verbose=2) and I was also able to run simulator

**Comment by j-ittner** [comment]
Perfect, glad it works now!
