### ISSUE TITLE
ModuleNotFoundError: No module named 'facet.data'; 'facet' is not a package

### ISSUE THREAD

**Issue by diogoalvesderesende** [BCG-Gamma/facet#220]
Hey!

First of all, this seems like a fantastic library! The visualizations are not notch. I am trying to replicate the example for my YouTube channel (I hope that is allowed), but I have issues importing the libraries. You can find the colab link below:
https://colab.research.google.com/drive/1mYqg8b4VhKvw5d_ExFqE3nge_yr5G_ql?usp=sharing

Here is the code error:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-ee3bda206c67> in <module>()
      4 from sklearndf.pipeline import RegressorPipelineDF
      5 from sklearndf.regression import RandomForestRegressorDF
----> 6 from facet.data import Sample
      7 from facet.selection import LearnerRanker, LearnerGrid

ModuleNotFoundError: No module named 'facet.data'; 'facet' is not a package

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by j-ittner** [comment]
Hi Diogo, thanks for your message!

Try installing `gamma-facet` not `facet`, then it should work.

Let us know if any more questions come up while you're exploring!

Jan

**Comment by j-ittner** [comment]
@diogoalvesderesende assuming the above has addressed your question - closing the issue for now.
