### ISSUE TITLE
gamma-facet==1.0.1 not compatible with latest shap==0.38.1

### ISSUE THREAD

**Issue by nibu147** [BCG-Gamma/facet#239]
Hello,
I installed gamma-facet==1.0.1, together with shap==0.38.1 (both latest versions).

When calling

`from facet.inspection import LearnerInspector`

I get the error
`ModuleNotFoundError: No module named 'shap.explainers.explainer'`
ar line 13 of **python3.8/site-packages/facet/inspection/_explainer.py** .

Are you able to provide a fix for this?

Thanks!

**Comment by joerg-schneider** [comment]
Hi @nibu147,

The 1.0.1 version you are using was only tested to work well with shap up until version 0.35.

We have recently added support for newer versions of shap: https://github.com/BCG-Gamma/facet/pull/213

This will be released as part of our next minor update soon.

May I ask why you manually specified a shap version? If possible for you, the downgrade of shap to 0.35.* will resolve this in the meantime.

Kind regards
Jörg

**Comment by nibu147** [comment]
Thank you Joerg for the answer! I'll downgrade shap.
