### ISSUE TITLE
README.rs dataset load can be automated for users

### ISSUE THREAD

**Issue by bhadurishirsesh** [BCG-Gamma/facet#308]
**Describe the bug**
README.rs mentions details of the dataset being used, but then imports a CSV that users might not have. Given the dataset is from sklearn, we can improve the code-block for more usability

**To Reproduce**
1. Go to README.rs
2. Follow steps till code block (line 110) and run the steps
3. Read CSV step (line 123) will raise a 'Filenot not found'

**Expected behavior**
Automated dataload directly from sklearn, with no read_csv step

**Screenshots**
(https://user-images.githubusercontent.com/91214098/134666712-7c22ecca-a556-42d1-9270-10b5e54c5eb5.png)

**Comment by j-ittner** [comment]
Closed by #310
