### ISSUE TITLE
cannot import LearnerInspector etc

### ISSUE THREAD

**Issue by BenOng93** [BCG-Gamma/facet#333]
**Describe the bug**
Not exhaustive list, but cannot run:
```
from facet.inspection import LearnerInspector
from facet.selection import LearnerRanker, LearnerGrid
```

But this runs:
`from facet.data import Sample`
Which means gamma-facet is installed. 

I copy/paste this code from the Facet github repo: https://github.com/BCG-Gamma/facet

**Comment by j-ittner** [comment]
Hi, did you try installing FACET using `pip` or `conda`?
