### ISSUE TITLE
Trouble importing LearnerInspector

### ISSUE THREAD

**Issue by MaxS-1** [BCG-Gamma/facet#334]
**Describe the bug**
I have trouble importing the LearnerInspector. When I try to import it, it throws the following error: 
_name 'catboost' is not defined_

The code I use for this import is: 
_from facet.inspection import LearnerInspector_
Update: the error also appears when I try to import facet.inspection (see full import output down below)

However, all of these import and (seem to) work without an issue:
_from facet.data import Sample_
_from facet.selection import LearnerRanker, LearnerGrid_
_from facet.validation import BootstrapCV_
_from facet.data.partition import ContinuousRangePartitioner_
_from facet.simulation import UnivariateProbabilitySimulator_
_from facet.simulation.viz import SimulationDrawer_
_from facet.crossfit import LearnerCrossfit_

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Spyder, installed via Anaconda
 - Python: 3.9.7
 - facet: 2.0.dev0
 - catboost: 0.26.1

Down below is the complete output, when I try to import face.inspection:

import facet.inspection
Traceback (most recent call last):

  Input In [19] in <cell line: 1>
    import facet.inspection

  File ~\Anaconda3\lib\site-packages\facet\inspection\__init__.py:8 in <module>
    from ._explainer import *

  File ~\Anaconda3\lib\site-packages\facet\inspection\_explainer.py:346 in <module>
    __tracker.validate()

  File ~\Anaconda3\lib\site-packages\pytools\api\_alltracker.py:200 in validate
    update_forward_references(obj, globals_=globals_)

  File ~\Anaconda3\lib\site-packages\pytools\api\_alltracker.py:328 in update_forward_references
    _update(obj)

  File ~\Anaconda3\lib\site-packages\pytools\api\_alltracker.py:315 in _update
    _update(member, local_ns=local_ns)

  File ~\Anaconda3\lib\site-packages\pytools\api\_alltracker.py:319 in _update
    _update_annotations(_obj, local_ns)

  File ~\Anaconda3\lib\site-packages\pytools\api\_alltracker.py:322 in _update_annotations
    annotations = get_type_hints(

  File ~\Anaconda3\lib\typing.py:1469 in get_type_hints
    value = _eval_type(value, globalns, localns)

  File ~\Anaconda3\lib\typing.py:292 in _eval_type
    ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)

  File ~\Anaconda3\lib\typing.py:292 in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)

  File ~\Anaconda3\lib\typing.py:290 in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)

  File ~\Anaconda3\lib\typing.py:551 in _evaluate
    eval(self.__forward_code__, globalns, localns),

  File <string>:1 in <module>

NameError: name 'catboost' is not defined

**Comment by MaxS-1** [comment]
I have used the following code to test catboost:

_import numpy_ 
_from catboost import CatBoostRegressor_

_dataset = numpy.array([[1,4,5,6],[4,5,6,7],[30,40,50,60],[20,15,85,60]])_
_train_labels = [1.2,3.4,9.5,24.5]_
_model = CatBoostRegressor(learning_rate=1, depth=6, loss_function='RMSE')_
_fit_model = model.fit(dataset, train_labels)_

_print(fit_model.get_params())_

The import worked and executed without any issue.

The code is taken from here:
https://catboost.ai/en/docs/installation/python-installation-test-catboost

**Comment by j-ittner** [comment]
Hi @MaxS-1, thanks for your sharing this.

I suggest you use facet 1.2.1 which is the latest stable version.

We're in the process of getting FACET 2 ready for release & will investigate your bug report.

**Comment by MaxS-1** [comment]
Dear @j-ittner 
Thank you very much for the advice. Changing the version of facet to 1.2.1 did the trick and now it works like a charm.

**Comment by j-ittner** [comment]
Glad to hear!

**Comment by j-ittner** [comment]
> Dear @j-ittner
> Thank you very much for the advice. Changing the version of facet to 1.2.1 did the trick and now it works like a charm.

@MaxS-1 actually I mistyped above - the latest version is 1.2.2. So in your conda environment or pip requirements I suggest you use `gamma-facet ~= 1.2.2`

**Comment by mikelgg93** [comment]
> > Dear @j-ittner
> > Thank you very much for the advice. Changing the version of facet to 1.2.1 did the trick and now it works like a charm.
> 
> @MaxS-1 actually I mistyped above - the latest version is 1.2.2. So in your conda environment or pip requirements I suggest you use `gamma-facet ~= 1.2.2`


Just passing by to mention that 1.2.2 is not available through pip.

`pip install -U gamma-facet== 1.2.2`


ERROR: Could not find a version that satisfies the requirement gamma-facet== (from versions: 1.0.0rc1, 1.0.0rc2, 1.0.1, 1.1.1, 1.1.2, 1.2.0rc1, 1.2.0, 1.2.1, 2.0.dev0)
ERROR: No matching distribution found for gamma-facet==

**Comment by j-ittner** [comment]
@mikelgg93 thanks - it is now! 1.2.2 is now the latest stable release available through pip and conda.
