### ISSUE TITLE
'LearnerRanker' object has no attribute '_ensure_fitted'

### ISSUE THREAD

**Issue by MaxS-1** [BCG-Gamma/facet#335]
### **Describe the bug**
I have encountered the issue that the attribute _ensure_fitted the LeanerRanker is calling is missing.
This also happens when I run the example code:

--------------------------------------------------------
**standard imports**
_import pandas as pd_
_from sklearn.model_selection import RepeatedKFold_

**some helpful imports from sklearndf**
_from sklearndf.pipeline import RegressorPipelineDF_
from sklearndf.regression import RandomForestRegressorDF_

**relevant FACET imports**
_from facet.data import Sample_
_from facet.selection import LearnerRanker, LearnerGrid_

**declaring url with data**
_data_url = 'https://web.stanford.edu/~hastie/Papers/LARS/diabetes.data'_

**importing data from url**
_diabetes_df = pd.read_csv(data_url, delimiter='\t').rename(_
    _renaming columns for better readability_
    _columns={_
        _'S1': 'TC', # total serum cholesterol_
        _'S2': 'LDL', # low-density lipoproteins_
        _'S3': 'HDL', # high-density lipoproteins_
        _'S4': 'TCH', # total cholesterol/ HDL_
        _'S5': 'LTG', # lamotrigine level_
        _'S6': 'GLU', # blood sugar level_
        _'Y': 'Disease_progression' # measure of progress since 1yr of baseline_
    _}_
_)_

**create FACET sample object**
_diabetes_sample = Sample(observations=diabetes_df, target_name="Disease_progression")_

**create a (trivial) pipeline for a random forest regressor**
_rnd_forest_reg = RegressorPipelineDF(_
    _regressor=RandomForestRegressorDF(n_estimators=200, random_state=42)_
_)_

**define grid of models which are "competing" against each other**
_rnd_forest_grid = [_
    _LearnerGrid(_
        _pipeline=rnd_forest_reg,_
        _learner_parameters={_
            _"min_samples_leaf": [8, 11, 15],_
            _"max_depth": [4, 5, 6],_
        _}_
    _),_
_]_

**create repeated k-fold CV iterator**
_rkf_cv = RepeatedKFold(n_splits=5, n_repeats=10, random_state=42)_

**rank your candidate models by performance (default is mean CV score - 2*SD)**
_ranker = LearnerRanker(_
    _grids=rnd_forest_grid, cv=rkf_cv, n_jobs=-3_
_).fit(sample=diabetes_sample)_

_get summary report_
_ranker.summary_report()_

-----------------------------------------------------------------------------
It is the last line, _ranker.summary_report()_ that produces the error 
AttributeError: 'LearnerRanker' object has no attribute '_ensure_fitted'

-----------------------------------------------------------------------------
Indeed, when I check the presence of the attribute it yields 'False':
_print(hasattr(LearnerRanker, '_ensure_fitted'))_

If I check the presence of ensure_fitted instead of _ensure_fitted, it yields 'True':
_print(hasattr(LearnerRanker, 'ensure_fitted'))_

**Comment by MaxS-1** [comment]
The issue has been solves by changing the version of facet to 1.2.1.
See issue Nr. 334.

**Comment by j-ittner** [comment]
Addressed in #334
