### ISSUE TITLE
 Support for scikit-learn models

### ISSUE THREAD

**Issue by jckkvs** [BCG-Gamma/facet#374]
**Is your feature request related to a problem? Please describe.**
I've encountered an issue when trying to use scikit-learn models with the facet library, specifically with the LearnerInspector class. The library currently only supports models of type SupervisedLearnerPipelineDF or SupervisedLearnerDF.

**Describe the solution you'd like**
I'd appreciate it if the facet library could extend support to include scikit-learn models. The API could potentially look like this:
```
from facet.inspection import LearnerInspector
inspector = LearnerInspector(
    model=scikit_learn_model_instance,
    n_jobs=-3
).fit(sample_data)
```

In this example, scikit_learn_model_instance could be any model instance from the scikit-learn library (RanfomForestRegressor, ).

**Describe alternatives you've considered**
One alternative is to manually adapt scikit-learn models to a format compatible with the facet library. However, native support would streamline the process, especially for those heavily using scikit-learn.

**Additional context**
Extending support for scikit-learn models would enhance the utility of the facet library, especially for data scientists and ML engineers who frequently use scikit-learn.

**Comment by mtsokol** [comment]
Hi @jckkvs,

Thank you for your feedback! I think what you're looking for is `NativeLearnerInspector` (introduced in the [latest release](https://github.com/BCG-Gamma/facet/pull/369)), which provides support for explaining native scikit-learn models:

```python
from facet.inspection import NativeLearnerInspector
inspector = NativeLearnerInspector(
    model=native_scikit_learn_model_instance,
    n_jobs=-3
)
```
Let me know if it solves your issue.

**Comment by jckkvs** [comment]
@j-ittner 

Thank you. I wasn't aware that there's already a feature called ```NativeLearnerInspector```. I'll definitely make use of it.

**Comment by jckkvs** [comment]
Thank you. I was unable to find the demo code, so I am providing the code that worked in my environment.

```
# standard imports
import pandas as pd
from sklearn.model_selection import RepeatedKFold, GridSearchCV

# some helpful imports from sklearndf
from sklearndf.pipeline import RegressorPipelineDF
from sklearndf.regression import RandomForestRegressorDF

# relevant FACET imports
from facet.data import Sample
from facet.selection import LearnerSelector, ParameterSpace

from sklearn.datasets import load_diabetes
X,y = load_diabetes(return_X_y=True)
data = load_diabetes()

X = pd.DataFrame(X)
X.columns  = data["feature_names"]
y = pd.DataFrame(y)
y.columns = ["target"]
diabetes_df = pd.concat([X,y], axis=1)

# create FACET sample object
diabetes_sample = Sample(observations=diabetes_df, target_name="target")

# create a (trivial) pipeline for a random forest regressor
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor(n_jobs=-1)
rfr.fit(X,y)

# fit the model inspector
from facet.inspection import NativeLearnerInspector
inspector = NativeLearnerInspector(
    model=rfr,
    n_jobs=-3
)

inspector.fit(diabetes_sample)

# visualise synergy as a matrix
from pytools.viz.matrix import MatrixDrawer
synergy_matrix = inspector.feature_synergy_matrix()
MatrixDrawer(style="matplot%").draw(synergy_matrix, title="Synergy Matrix")

# visualise redundancy as a matrix
redundancy_matrix = inspector.feature_redundancy_matrix()
MatrixDrawer(style="matplot%").draw(redundancy_matrix, title="Redundancy Matrix")

# visualise redundancy using a dendrogram
import matplotlib
from pytools.viz.dendrogram import DendrogramDrawer
redundancy = inspector.feature_redundancy_linkage()
DendrogramDrawer().draw(data=redundancy, title="Redundancy Dendrogram")
```
